# Generated by Django 6.0.1 on 2026-01-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Platform Admin'), ('owner', 'Theatre Owner'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
