data = {
    "actors": [
        "Mammootty",
        "Mohanlal",
        "Fahadh Faasil",
        "Prithviraj Sukumaran",
        "Manju Warrier",
        "Dulquer Salmaan",
        "Nivin Pauly",
        "Tovino Thomas",
        "Parvathy Thiruvothu",
        "Kunchacko Boban",
        "Jayasurya",
        "Asif Ali",
        "Nazriya Nazim",
        "Suraj Venjaramoodu",
        "Shane Nigam",
        "Soubin Shahir",
        "Nithya Menen",
        "Indrajith Sukumaran",
        "Biju Menon",
        "Keerthy Suresh",
        "Siddique",
        "Murali Gopy",
        "Nimisha Sajayan",
        "Shine Tom Chacko",
        "Arjun Ashokan",
        "Aishwarya Lekshmi",
        "Antony Varghese",
        "Sreenath Bhasi",
        "Vinayakan",
        "Anaswara Rajan",
        "Sunny Wayne",
        "Chemban Vinod Jose",
        "Mamitha Baiju",
        "Saiju Kurup",
        "Joju George",
        "Anna Ben",
        "Dileep",
        "Suresh Gopi",
        "Grace Antony",
        "Jayaram",
    ],
    "directors": [
        "Basil Joseph",
        "Lijo Jose Pellissery",
        "Dileesh Pothan",
        "Amal Neerad",
        "Anwar Rasheed",
        "Alphonse Puthren",
        "Vineeth Sreenivasan",
        "Jeethu Joseph",
        "Priyadarshan",
        "Sathyan Anthikad",
        "Blessy",
        "Rosshan Andrrews",
        "Aashiq Abu",
        "Khalid Rahman",
        "Ratish Ambat",
        "Mahesh Narayanan",
        "Chidambaram",
        "Jithu Madhavan",
        "Tinu Pappachan",
        "Rohit MG Krishnan",
    ],
    "movies": [
        "Manjummel Boys",
        "Marakkar",
        "Bramayugam",
        "Premalu",
        "Aadujeevitham",
        "Aavesham",
        "Drishyam",
        "Lucifer",
        "Kumbalangi Nights",
        "Maheshinte Prathikaaram",
        "Thallumaala",
        "Minnal Murali",
        "Bangalore Days",
        "Premam",
        "Bheeshma Parvam",
        "Kannur Squad",
        "2018",
        "Home",
        "Jaya Jaya Jaya Jaya Hey",
        "Kaathal - The Core",
    ],
}

