# Generated by Django 6.0.1 on 2026-01-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviecast_slug_alter_moviecast_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecast',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
