# Generated by Django 6.0.1 on 2026-01-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_moviecast_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecast',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
